### PR TITLE
add travis testing and new tool installation method

### PR DESCRIPTION
**Pull request by bgruening**
Greg you need to activate travis testing in the github preference setting of this repository. If you do this every additional modification will be tested automatically.

### CODE REVIEW

**Comment by bgruening** [comment]
Greg for some reason the installation from the testtoolshed is broken. I added a random tool from the toolshed and this works. So this is just a WIP.

**Comment by gregvonkuster** [comment]
Thanks for taking a look at making this work @bgruening!  Please let me know if there is anything I can do to help out.

**Comment by bgruening** [comment]
Any reason all these packages are not in MTS?
Do you follow TS development and maybe have any hint why installation over the API seems to be broken in TTS?

**Comment by gregvonkuster** [comment]
There are a few things we want to improve in the underlying icqsol package before we move these to the MTS. 

 I try to follow TS development, although I'm not aware of much that is happening outside of planemo, so maybe I've missed some things.  For the past several weeks I've only installed from my local TS and the Mts and I have not been using the API for installations.  I was installing from the TTS until about the middle of January and don't remember any problems, but I wasn't using the API then either.  So unfortunately I'm not sure when the installation API was broken.  :(

**Comment by gregvonkuster** [comment]
@bgruening I've set up Travis testing for this repository.  I've also made you a collaborator in case that helps.  Thanks for your help with this!

**Comment by bgruening** [comment]
thanks @gregvonkuster!

@davebx do you know what was introduced in the TTS which prevents from installing via the API?

**Comment by bgruening** [comment]
@gregvonkuster travis does not seem to be enabled and I can not change the setting for this repo. 

Nevertheless, I don't think these changes will break anything that has worked before. But would be nice to get testing enabled.

**Pull request merged**
