### PR TITLE
19.01

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @gregvonkuster 
Tests are passing but maybe we should also check the tools at some point.

**Comment by gregvonkuster** [comment]
Thanks @bgruening ;)

**Comment by bgruening** [comment]
Seem you need to reconnect the repo: https://quay.io/repository/gregvonkuster/galaxy-csg?tab=info

**Comment by gregvonkuster** [comment]
@bgruening These are all public repos, so the is not something like an ssh key problem, right?  I'm not sure how to fix this.

**Comment by bgruening** [comment]
You own the quay.io repos isn't it? This is a configuration think on quay.io. I can do this if you give me admin access to it.

**Comment by gregvonkuster** [comment]
Done - I'll make sure to check what you've done to fix this. ;)

**Comment by bgruening** [comment]
Mh, I also need to have privs for this repo I guess.

You can simply go to https://quay.io/repository/gregvonkuster/galaxy-csg?tab=builds and follow the "Create Build Trigger" button.

**Comment by gregvonkuster** [comment]
You do have Admin on that one as well.

**Comment by bgruening** [comment]
Done. Container available.

**Pull request merged**
